#define PTOK_ENDS                            1
#define PTOK_IDENTIFIER                      2
#define PTOK_STAR                            3
#define PTOK_KW_VOID                         4
#define PTOK_KW_FLOAT                        5
#define PTOK_KW_DOUBLE                       6
#define PTOK_KW_LONG                         7
#define PTOK_KW_UNSIGNED                     8
#define PTOK_KW_SIGNED                       9
#define PTOK_KW_INT                         10
#define PTOK_KW_SHORT                       11
#define PTOK_KW_CHAR                        12
#define PTOK_OPAREN                         13
#define PTOK_CPAREN                         14
#define PTOK_OBRACE                         15
#define PTOK_CBRACE                         16
